image: ruby:2.7.2

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - ./bin/setup
    - rake test

deploy:
  stage: deploy
  only:
    - master
  script:
    - gem install dpl --pre
    - dpl rubygems --api_key $K8S_SECRET_RUBYGEMS_API_KEY